---
title: lanark.house
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: This repository and site serve as a way to document and inventory every
  step of my new home purchase process.
baseurl: ''
url: ''
theme: minima
plugins:
- jekyll-remote-theme
remote_theme: jekyll/minima@2.5-stable
