name: Create Pull Request

on:
  push:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.event.head_commit.author.username == 'google-labs-jules[bot]' # Condition updated here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for existing PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          echo "Checking for PR on branch $BRANCH_NAME"
          # Ensure the branch name doesn't contain problematic characters for a filename
          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9_.-]/_/g')
          PR_NUMBER_FILE="pr_number_${SANITIZED_BRANCH_NAME}.txt"
          gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number // empty' > "$PR_NUMBER_FILE"
          cat "$PR_NUMBER_FILE"

      - name: Create PR if none exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9_.-]/_/g')
          PR_NUMBER_FILE="pr_number_${SANITIZED_BRANCH_NAME}.txt"
          if [ ! -s "$PR_NUMBER_FILE" ]; then
            echo "No PR found for $BRANCH_NAME. Creating one now."
            # Determine the base branch (default branch of the repository)
            BASE_BRANCH=$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)
            gh pr create --base "$BASE_BRANCH" --head "$BRANCH_NAME" --title "PR for $BRANCH_NAME" --body "Automated PR created for changes in $BRANCH_NAME" --label 'google-labs-jules[bot]'
          else
            echo "PR already exists for $BRANCH_NAME. Skipping creation."
          fi
          # Clean up the temporary file
          rm -f "$PR_NUMBER_FILE"