name: Rename .markdown files to .md

on: [push]

jobs:
  rename-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back to the repository
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Find and rename .markdown files to .md
        run: |
          shopt -s globstar nullglob
          changed=0
          for file in **/*.markdown; do
            [ -f "$file" ] || continue
            new="${file%.markdown}.md"
            git mv "$file" "$new"
            changed=1
          done
          if [ $changed -eq 1 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: rename .markdown files to .md"
            git push
          fi
