name: Create transparency report for posts

on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/post-transparency.yaml
      - _posts/**

jobs:
  audit-pdf:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-path: .github/workflows/post-transparency.yaml, _posts/**
