name: Create transparency report

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:
  push:
    paths: [.github/workflows/transparency.yaml]

jobs:
  audit-pdf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: screenshot listing page
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://douglashomes.net/new-home/fernie-3-2/
          mode: wholePage
          output: fernie-3-2.png
      - name: audit the PDF
        run: |
          curl -LO --silent https://douglashomes.net/wp-content/uploads/2024/08/Fernie-204LWC.pdf
          sha256sum Fernie-204LWC.pdf >> $GITHUB_STEP_OUTPUT
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'updating the lanark landing listing @ 204 Langwell Common SE'
